name: Deploy Web Configurator

on:
  push:
    branches: [ main ]
    paths:
      - 'config/config.template.py'
      - 'web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          
      - name: Generate config schema
        run: |
          python config/generate_config_schema.py
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web